USE freeuni;

DROP TABLE IF EXISTS voting_data;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS friendship_data;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS badges;
DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS statuses;

